const bookings={qvm:{title:'女王市场官网',label:'运营信息',note:'营业日与摊位',url:'https://qvm.com.au/'},'gardens-ngv':{title:'NGV 官方预约',label:'场馆预约',note:'入场 / 特展复核',url:'https://www.ngv.vic.gov.au/visit/'},healesville:{title:'Healesville Sanctuary',label:'官方购票',note:'门票与开放时间',url:'https://www.zoo.org.au/healesville/tickets/'},balloon:{title:'Yarra Valley 热气球',label:'运营商预约',note:'天气与取消条款',url:'https://www.hotairballooning.com.au/yarravalley/'},'tidal-river':{title:'Tidal River 营地',label:'Parks Victoria 预订',note:'住宿 / 车位复核',url:'https://bookings.parks.vic.gov.au/book/wilsons-prom-accommodation'},penguin:{title:'Penguin Parade',label:'官方购票',note:'票档与到场时间',url:'https://www.penguins.org.au/buy-tickets/'},'hot-springs':{title:'Peninsula Hot Springs',label:'官方预约',note:'浴场时段',url:'https://www.peninsulahotsprings.com/book/'},'cape-otway':{title:'Cape Otway Lightstation',label:'官网 / 购票',note:'开放、道路与入场复核',url:'https://www.lightstation.com/'},'learn-to-fly':{title:'Learn To Fly Melbourne',label:'官方咨询 / 预约',note:'体验飞行与天气条款',url:'https://learntofly.edu.au/contact/'}};
const meta={'city-arrival':['main','城市漫步','地标与河岸'],'st-patricks':['optional','景点','哥特建筑'],qvm:['optional','市场','本地食材'],hosier:['optional','景点','街头艺术'],'gardens-ngv':['main','景点群','园林与艺术'],fitzroy:['optional','街区','咖啡与小店'],'ngv-library':['optional','景点群','艺术与人文'],yarravalley:['main','行程节点','山谷与葡萄园'],healesville:['main','景点','本土动物'],balloon:['main','体验','日出飞行'],'tidal-river':['main','景点','河口与野生动物'],squeaky:['main','景点','石英白沙'],bigdrift:['optional','景点','沙丘日落'],lilly:['optional','徒步','雨林生态'],nobbies:['main','景点','海豹与海鸟'],penguin:['main','体验','小蓝企鹅'],woolamai:['optional','景点','海岸徒步'],'hot-springs':['main','体验','地热泡池'],surfcoast:['optional','景点群','冲浪海岸'],splitpoint:['main','景点群','灯塔与大洋路'],erskine:['optional','景点','雨林瀑布'],kennett:['optional','景点','野生考拉'],'cape-otway':['main','景点群','森林与灯塔'],gibson:['optional','景点','近海崖壁'],apostles:['main','景点','海蚀岩柱'],lochard:['main','景点','峡谷海湾'],londonbridge:['main','景点','坍塌海拱'],grotto:['optional','景点','天然石窟'],bayislands:['main','景点','海岸岩柱'],'learn-to-fly':['optional','体验','亲手操控飞机'],departure:['main','行程节点','返程留白']};
const english={'city-arrival':'Federation Square / Yarra River / Flinders Street Station','gardens-ngv':'Royal Botanic Gardens Victoria / NGV / ACMI','ngv-library':'NGV / State Library Victoria','tidal-river':'Tidal River / Norman Beach',squeaky:'Squeaky Beach / Whisky Bay',bigdrift:'Big Drift',lilly:'Lilly Pilly Gully',nobbies:'The Nobbies / Seal Rocks',woolamai:'Cape Woolamai / Churchill Island',surfcoast:'Bells Beach / Torquay',splitpoint:'Split Point Lighthouse / Memorial Arch / Lorne','cape-otway':'Great Otway National Park / Cape Otway Lightstation',londonbridge:'London Bridge',grotto:'The Grotto',bayislands:'Bay of Islands','learn-to-fly':'Moorabbin Airport'};
const directImages={squeaky:'https://upload.wikimedia.org/wikipedia/commons/3/33/Squeaky_beach_wilsons_prom.JPG'};
const confirmedPlaceIds=new Set(['tidal-river','penguin']);
const pendingBookingIds=new Set(['qvm','gardens-ngv','healesville','balloon','hot-springs','cape-otway','learn-to-fly']);
const confirmations={
  0:[{title:'朋友家 · 已确认住宿',detail:'墨尔本（Melbourne）· 9 月 24 日至 27 日',files:[]}],
  1:[{title:'朋友家 · 已确认住宿',detail:'墨尔本（Melbourne）· 9 月 24 日至 27 日',files:[]}],
  2:[{title:'朋友家 · 已确认住宿',detail:'墨尔本（Melbourne）· 9 月 24 日至 27 日',files:[]}],
  3:[{title:'亚拉河谷酒店（Yarra Valley Lodge）· 已确认住宿',detail:'9 月 27 日至 28 日',files:[['英文确认函','assets/bookings/stay-2026-09-27-亚拉河谷酒店酒店英文确认函.pdf'],['中英文确认函','assets/bookings/stay-2026-09-27-亚拉河谷酒店酒店中英文确认函.pdf']]}],
  4:[{title:'舞会海岸度假别墅（Prom Coast Holiday Lodge）· 已确认住宿',detail:'9 月 28 日至 29 日 · Waratah North',files:[['英文确认单','assets/bookings/stay-2026-09-28-wilsons-prom-english.pdf'],['中文确认单','assets/bookings/stay-2026-09-28-wilsons-prom-chinese.pdf']]}],
  5:[{title:'菲利普岛卡罗哈假日度假村（Kaloha Holiday Resort）· 已确认住宿',detail:'9 月 29 日至 30 日',files:[['英文确认函','assets/bookings/stay-2026-09-29-菲利普岛卡罗哈假日度假村酒店英文确认函.pdf'],['中英文确认函','assets/bookings/stay-2026-09-29-菲利普岛卡罗哈假日度假村酒店中英文确认函.pdf']]},{title:'企鹅归巢终极探险 · 已确认门票',detail:'9 月 29 日；到场时间以票面为准',files:[['查看 / 下载票券','assets/bookings/ticket-2026-09-29-penguin-parade-ultimate-adventure.pdf']]}],
  6:[{title:'墨尔本亚特兰蒂斯酒店（Atlantis Hotel Melbourne）· 已确认住宿',detail:'9 月 30 日至 10 月 1 日',files:[['英文确认函','assets/bookings/stay-2026-09-30-墨尔本亚特兰蒂斯酒店酒店英文确认函.pdf'],['中英文确认函','assets/bookings/stay-2026-09-30-墨尔本亚特兰蒂斯酒店酒店中英文确认函.pdf']]}],
  7:[{title:'曼特拉洛恩酒店（Mantra Lorne）· 已确认住宿',detail:'10 月 1 日至 2 日',files:[['英文确认函','assets/bookings/stay-2026-10-01-曼特拉洛恩酒店酒店英文确认函.pdf'],['中英文确认函','assets/bookings/stay-2026-10-01-曼特拉洛恩酒店酒店中英文确认函.pdf']]}],
  8:[{title:'无敌海景汽车旅店（A Great Ocean View Motel）· 已确认住宿',detail:'10 月 2 日至 3 日',files:[['英文确认函','assets/bookings/stay-2026-10-02-无敌海景汽车旅店酒店英文确认函.pdf'],['中英文确认函','assets/bookings/stay-2026-10-02-无敌海景汽车旅店酒店中英文确认函.pdf']]}],
  9:[{title:'南海洋汽车旅馆（Southern Ocean Motor Inn）· 已确认住宿',detail:'10 月 3 日至 4 日',files:[['英文确认函','assets/bookings/stay-2026-10-03-南海洋汽车旅馆酒店英文确认函.pdf'],['中英文确认函','assets/bookings/stay-2026-10-03-南海洋汽车旅馆酒店中英文确认函.pdf']]}],
  10:[{title:'墨尔本小柯林斯智选假日酒店（Holiday Inn Express Melbourne Little Collins by IHG）· 已确认住宿',detail:'10 月 4 日至 6 日',files:[['英文确认函','assets/bookings/stay-2026-10-04-洲际酒店集团智选假日酒店墨尔本小柯林斯酒店英文确认函.pdf'],['中英文确认函','assets/bookings/stay-2026-10-04-洲际酒店集团智选假日酒店墨尔本小柯林斯酒店中英文确认函.pdf']]}],
  11:[{title:'墨尔本小柯林斯智选假日酒店（Holiday Inn Express Melbourne Little Collins by IHG）· 已确认住宿',detail:'10 月 4 日至 6 日；确认单见上一日',files:[]}]
};
function p(id,name,en,wiki,source,intro,guide,location,food,feature,caution){const [role,category,highlight]=meta[id]||['main','景点','行程亮点'];return{id,name,en,displayEn:english[id]||en,wiki,source,intro,guide,location,food,feature,caution,role,category,highlight,image:directImages[id]||'',booking:bookings[id]||null,confirmed:confirmedPlaceIds.has(id)};}
const stay=[
 '住宿已确认：朋友家（Melbourne，9 月 24 日至 27 日）','住宿已确认：朋友家（Melbourne，9 月 24 日至 27 日）','住宿已确认：朋友家（Melbourne，9 月 24 日至 27 日）','住宿已确认：亚拉河谷酒店（Yarra Valley Lodge，9 月 27 日至 28 日）','住宿已确认：舞会海岸度假别墅（Prom Coast Holiday Lodge，9 月 28 日至 29 日）','住宿已确认：菲利普岛卡罗哈假日度假村（Kaloha Holiday Resort，9 月 29 日至 30 日）','住宿已确认：墨尔本亚特兰蒂斯酒店（Atlantis Hotel Melbourne，9 月 30 日至 10 月 1 日）','住宿已确认：曼特拉洛恩酒店（Mantra Lorne，10 月 1 日至 2 日）','住宿已确认：无敌海景汽车旅店（A Great Ocean View Motel，10 月 2 日至 3 日）','住宿已确认：南海洋汽车旅馆（Southern Ocean Motor Inn，10 月 3 日至 4 日）','住宿已确认：墨尔本小柯林斯智选假日酒店（Holiday Inn Express Melbourne Little Collins by IHG，10 月 4 日至 6 日）','住宿已确认：墨尔本小柯林斯智选假日酒店（Holiday Inn Express Melbourne Little Collins by IHG，10 月 4 日至 6 日）','住宿：不安排，返程日'];
const pace=['到达日：只保留主线，按精力决定备选。','节奏舒缓：备选可按天气与体力取舍。','留白日：不离开墨尔本，为后段连续转场储备体力。','转场日：包车出城，先保证动物保护区闭园前抵达。','条件替换日：热气球正常起飞则只做潮汐河黄昏；取消且傍晚转为低风干燥时，改走大沙丘日落。','紧凑日：威尔逊岬只取代表性海湾，午后必须转场赴菲利普岛。','转场日：丘吉尔岛 / 伍拉迈角为备选，半岛温泉为主线。','自驾日：完整走大洋路东段；停靠点主动收缩，不搭乘轮渡。','节奏适中：奥特维国家公园与海角灯塔为主线；瀑布、考拉观察为备选。','紧凑日：吉布森台阶受海况影响，十二门徒与峡谷优先，并将日落留给十二门徒。','紧凑日：西段只选两处主线观景点，随后内陆回城。','缓冲日：飞行体验之外的人文场馆均为备选。','返程日：不再安排景点。'];
const days=[
 {date:'2026-09-24',label:'D1',dateText:'09.24 · 周四',title:'抵达墨尔本',route:'不租车 · 市中心轻量步行 · 住 Melbourne CBD',places:[
  p('city-arrival','墨尔本城市地标散步','Melbourne City Walk','Flinders_Street_railway_station','https://www.visitmelbourne.com/','把第一天留给调时差：联邦广场、雅拉河和弗林德斯街车站可随体力任意串联。','联邦广场 → 雅拉河河岸 → 弗林德斯街车站；到得晚仅选一段河岸步行。','Melbourne CBD；各点在免费电车区或步行范围。','咖啡与轻食优先，按落地时间决定。','城市地标、河岸与百年车站','抵达日不赶景点；疲劳时直接删减。'),
  p('st-patricks','圣派翠克大教堂（备选）',"St Patrick's Cathedral","St_Patrick's_Cathedral,_Melbourne",'https://melbournecathedral.org.au/','抵达较早且精力尚可时的顺路备选。','入内前查看开放与礼拜安排；保持安静、注意着装。','1 Cathedral Place, East Melbourne。','CBD 或东区晚餐。','哥特式尖塔与彩窗','开放时段可能因礼拜调整（预计）。')]},
 {date:'2026-09-25',label:'D2',dateText:'09.25 · 周五',title:'墨尔本市区启动',route:'免费电车区 · 市场、巷弄、园林 · 傍晚 Fitzroy',places:[
  p('qvm','维多利亚女王市场','Queen Victoria Market','Queen_Victoria_Market','https://qvm.com.au/','历史市场是市区启动的生活化一站：农产、熟食与摊位构成墨尔本的日常切面。','先确认当日开市时间；早餐或补给在这里完成。','Queen St & Victoria St, Melbourne。','市场熟食、烘焙与咖啡。','历史露天市场与本地食材','不同日期营业摊位和夜市安排不同（预计）。'),
  p('hosier','涂鸦巷','Hosier Lane','Hosier_Lane','https://www.visitmelbourne.com/regions/melbourne/see-and-do/art-and-culture/street-art/hosier-lane','持续变化的街头艺术巷道，把它当作城市纹理，而非固定展览。','从 Flinders Street 一侧进入；注意车辆，短停即可。','Hosier Lane, Melbourne CBD。','周边巷弄咖啡馆。','高密度街头艺术','墙绘与既往照片不同属正常。'),
  p('gardens-ngv','皇家植物园与艺术馆群','Royal Botanic Gardens Victoria','Royal_Botanic_Gardens_Victoria','https://www.rbg.vic.gov.au/','用植物园放慢市区节奏；雨天改逛 NGV 或 ACMI。','植物园走小环即可；展馆预约与闭馆时间出发前复核。','Birdwood Ave, South Yarra；NGV 与 ACMI 在市中心周边。','Southbank 或 CBD 午餐。','英式园林、艺术与银幕文化','展览政策及票务须复核（预计）。'),
  p('fitzroy','Fitzroy 傍晚散步','Fitzroy, Victoria','Fitzroy,_Victoria','https://www.visitmelbourne.com/regions/melbourne/destinations/fitzroy','作为松弛收尾，不预设路径。','沿 Brunswick Street 或 Gertrude Street 随走随停。','Melbourne CBD 以北。','咖啡、酒吧和小店临场选择。','文艺街区与独立店铺','不安排硬性景点。')]},
 {date:'2026-09-26',label:'D3',dateText:'09.26 · 周六',title:'墨尔本留白日',route:'全日在 Melbourne · 不取车、不转场 · 为后段储备体力',places:[
  p('gardens-ngv','NGV 与皇家植物园','National Gallery of Victoria','National_Gallery_of_Victoria','https://www.ngv.vic.gov.au/','这一天明确留在墨尔本：将 D2 未完成的植物园与艺术馆放到白天完成，不提前进入亚拉谷。','只选一个主展馆或一段园林；晚间回酒店整理包车行李。','St Kilda Rd / South Yarra，均在市区交通范围。','Southbank 午餐或 CBD 晚餐。','艺术收藏与城市园林','展览和预约政策须出发前复核（预计）。'),
  p('ngv-library','维多利亚州立图书馆（备选）','State Library Victoria','State_Library_Victoria','https://www.slv.vic.gov.au/','如不想重复 NGV，可改去州立图书馆；目的只是留在市区并保持轻松。','与 NGV 二选一，别把留白日重新塞满。','328 Swanston St, Melbourne。','CBD 咖啡馆与轻食。','穹顶阅览室与城市人文','开放时段以官网为准（预计）。')]},
 {date:'2026-09-27',label:'D4',dateText:'09.27 · 周日',title:'墨尔本至亚拉谷',route:'包车 · Melbourne → Yarra Valley → Healesville Sanctuary · 住 Yarra Valley',places:[
  p('yarravalley','亚拉谷转场','Yarra Valley','Yarra_Valley','https://www.visityarravalley.com.au/','从墨尔本正式动身，沿山谷进入次日热气球集合区。','不把酒庄排得过多；以安全行车为先。','Melbourne → Yarra Valley，车程约 1 小时（预计）。','Healesville 小镇晚餐或酒店简餐。','葡萄园与山谷公路','次晨很早集合，晚间不要安排过晚。'),
  p('healesville','希尔斯维尔野生动物保护区','Healesville Sanctuary','Healesville_Sanctuary','https://www.zoo.org.au/healesville/','以澳洲本土动物为主的保护区；将鸭嘴兽、考拉、袋鼠等留作当日重点。','提前查看闭园和动物讲解时间；入园先确认鸭嘴兽展区。','Badger Creek Rd, Healesville。','园内简餐或 Healesville 小镇晚餐。','澳洲本土动物与保育展示','周末客流与展示安排可能变化（预计）。')]},
 {date:'2026-09-28',label:'D5',dateText:'09.28 · 周一',title:'热气球后抵达威尔逊岬',route:'清晨热气球 · 午后包车转场 · 住 Prom Coast Holiday Lodge（Waratah North）',places:[
  p('balloon','亚拉谷热气球','Yarra Valley','Yarra_Valley','https://www.hotairballooning.com.au/yarravalley/','日出前集合的飞行体验予以保留；它是整条路线中最不可替代的体验之一。','前一晚确认天气和集合点；取消仍在中午前转场。','Yarra Valley；具体起降地由运营方按天气决定。','飞行后按运营方安排早餐或在小镇补给。','日出葡萄园与山谷视野','是否起飞完全由天气决定。'),
  p('tidal-river','潮汐河与诺曼海滩','Tidal River, Victoria','Tidal_River,_Victoria','https://www.parks.vic.gov.au/places-to-see/parks/wilsons-promontory-national-park','热气球成功起飞时，经 Leongatha、Foster 抵达威尔逊岬后只安排潮汐河与诺曼海滩日落；不再叠加徒步。','Tidal River 无油站，务必在 Foster 前后补满；入住后在海滩附近看日落即可。','Wilsons Promontory National Park 南端。','Foster 午餐与补给；营地自备或简餐。','河口、海滩与黄昏野生动物','入口工程公告覆盖此日期，可能有临时交通管制；出发前复核。'),
  p('bigdrift','大沙丘（热气球天气替换项）','Big Drift','Wilsons_Promontory_National_Park','https://www.parks.vic.gov.au/places-to-see/parks/wilsons-promontory-national-park','仅在热气球因晨雾、低云或运营调度取消，且傍晚天气转为干燥、低风时替换执行；热气球正常起飞时不去。','下午抵达后走至沙丘看日落，务必在天黑前返程；带头灯、防风层与水。','Big Drift carpark，返程回舞会海岸度假别墅（Prom Coast Holiday Lodge）。','自备零食。','风积沙丘与日落天际线','强风、降雨或雷暴取消热气球时，通常也不适合前往；不能自动替换。')]},
 {date:'2026-09-29',label:'D6',dateText:'09.29 · 周二',title:'威尔逊岬至菲利普岛',route:'上午代表性海湾 · 午后约 2.5—3 小时转场 · Nobbies 与企鹅归巢',places:[
  p('squeaky','吱吱海滩与威士忌湾','Squeaky Beach','Squeaky_Beach','https://www.parks.vic.gov.au/places-to-see/parks/wilsons-promontory-national-park/things-to-do/squeaky-beach','将威尔逊岬压缩为最具代表性的花岗岩海湾与石英白沙；这是与大洋路不重复的部分。','早到 Squeaky Beach；停车紧张或天气差时只保留一个海湾。中午前离开。','Wilsons Promontory 西侧，邻近 Tidal River。','带水与野餐；Foster 再补给。','石英白沙、花岗岩与海湾','无救生员巡逻且可能有离岸流；不把此处当游泳任务。'),
  p('lilly','莉莉皮里谷（备选）','Lilly Pilly Gully','Wilsons_Promontory_National_Park','https://www.parks.vic.gov.au/places-to-see/parks/wilsons-promontory-national-park/things-to-do/day-walks','只在前一天未做大沙丘、且上午时间充足时才考虑的短线。','与海湾二选一或缩短步行，不能影响午后转场。','Tidal River 周边。','出发前补水。','蕨类雨林与原生生态','步道状态以现场公告为准。'),
  p('nobbies','诺比斯中心与海豹岩','The Nobbies','The_Nobbies,_Victoria','https://www.penguins.org.au/visit/important-information/','抵岛后先到木栈道看海豹岩、海鸟与南岸海景，再进入企鹅归巢环节。','白天走栈道；傍晚确认道路与停车。','Phillip Island 西南端，靠近 Summerland。','在 Cowes 或途中解决正餐。','海豹岩、海鸟与海蚀海岸','中心设施与栈道开放情况出发前复核。'),
  p('penguin','小蓝企鹅归巢','Penguin Parade','Penguin_Parade','https://www.penguins.org.au/public/attractions/penguin-parade/','小蓝企鹅在日落后从海上回到洞穴，是当晚不可压缩、须预约执行的体验。','提前订票；按票面时间到达，带防风保暖层。日落后禁止拍照或录像。','1019 Ventnor Rd, Summerlands, VIC 3922。','在 Cowes / Newhaven 提前晚餐。','小蓝企鹅归巢','到场时间以票面及官方当日提醒为准。')]},
 {date:'2026-09-30',label:'D7',dateText:'09.30 · 周三',title:'菲利普岛回墨尔本',route:'Churchill Island / Cape Woolamai 备选 · 午后 Peninsula Hot Springs · 回 Melbourne',places:[
  p('woolamai','伍拉迈角或丘吉尔岛（备选）','Cape Woolamai / Churchill Island','Cape_Woolamai','https://www.penguins.org.au/visit/','两者只能选一：想活动选伍拉迈角短线；风雨或偏好人文时改丘吉尔岛历史农场。','上午短停即可，午后温泉预约为优先。','Phillip Island 东南端 / Churchill Island。','Cowes 早餐，午餐后离岛。','花岗岩海岸或历史农场','不建议同时完成两处。'),
  p('hot-springs','半岛温泉','Peninsula Hot Springs','Peninsula_Hot_Springs','https://www.peninsulahotsprings.com/','从菲利普岛回程，在莫宁顿半岛以地热浴场收束前半程。','提前预约指定时段；带泳衣、拖鞋和保暖衣物。','Springs Lane, Fingal。','温泉场馆餐饮或 Rye 晚餐。','天然地热温泉与户外泡池','票务、开放与服务时段须复核。')]},
 {date:'2026-10-01',label:'D8',dateText:'10.01 · 周四',title:'自驾进入大洋路',route:'租车自驾 · Melbourne → Surf Coast → Split Point → Memorial Arch → Lorne · 不乘船',places:[
  p('surfcoast','冲浪海岸（备选）','Bells Beach / Torquay','Bells_Beach,_Victoria','https://www.visitvictoria.com/regions/great-ocean-road','完整经过大洋路东段，但不再逐个停靠 Barwon Heads、Bells Beach 与 Torquay。','对冲浪有兴趣才选 Bells Beach；否则补给后直接前往灯塔与拱门。','Melbourne → Torquay → Aireys Inlet。','Torquay 简餐或咖啡。','冲浪海岸与礁岩浪线','海滩观景不等于适合下水。'),
  p('splitpoint','分角灯塔、纪念拱门与洛恩','Split Point Lighthouse / Memorial Arch / Lorne','Split_Point_Lighthouse','https://www.greatoceanroadauthority.vic.gov.au/','保留东段最具辨识度的灯塔与大洋路入口标志，天黑前抵达洛恩。','先确认灯塔登塔开放；纪念拱门短停拍照，不为小镇反复停车。','Aireys Inlet → Eastern View → Lorne。','Lorne 海滨晚餐。','白色灯塔与大洋路入口标志','自驾第一天保持保守节奏，沿线多弯。')]},
 {date:'2026-10-02',label:'D9',dateText:'10.02 · 周五',title:'奥特维国家公园与海角灯塔',route:'Lorne →（Erskine / Kennett 备选）→ Great Otway National Park → Cape Otway Lightstation → Apollo Bay',places:[
  p('erskine','厄斯金瀑布（备选）','Erskine Falls','Erskine_Falls','https://www.parks.vic.gov.au/places-to-see/parks/great-otway-national-park','洛恩腹地的雨林瀑布；若前日抵达较晚或天气不好，它是当天第一个可删减点。','台阶湿滑，暴雨后按封闭信息调整。','Erskine Falls Access Rd, Lorne hinterland。','Lorne 早餐后再决定。','雨林瀑布与蕨类谷地','道路与步道状态可能变化（预计）。'),
  p('kennett','肯尼特河看考拉（备选）','Kennett River','Kennett_River','https://www.visitvictoria.com/regions/great-ocean-road','野生考拉观察不保证；因前段已有保护区动物体验，将其降为顺路备选。','抬头看树冠、保持距离，不投喂；路边停车注意来车。','Kennett River, Great Ocean Road。','仅作轻补给，不作为正餐目的地。','野生考拉与桉树林','动物出现具有随机性（预计）。'),
  p('cape-otway','奥特维国家公园与奥特维海角灯塔','Great Otway National Park / Cape Otway Lightstation','Cape_Otway_Lightstation','https://www.parks.vic.gov.au/places-to-see/parks/great-otway-national-park','这是 10 月 2 日固定主线：穿越温带雨林后驶往海角灯塔；不再安排 Maits Rest。','灯塔是从主路向南的专程支线，先确认道路、开放和入场；停靠备选点过久时优先删备选。','Cape Otway Lightstation 位于 Apollo Bay 以西约 35 km，距大洋路约 12 km 支线。','抵达 Apollo Bay 后晚餐；沿途只作轻补给。','温带森林、海角与历史灯塔','开放、收费与道路条件须出发前复核。')]},
 {date:'2026-10-03',label:'D10',dateText:'10.03 · 周六',title:'十二门徒与坎贝尔港',route:'Apollo Bay → Gibson Steps（备选）→ Twelve Apostles → Loch Ard Gorge · 住 Port Campbell',places:[
  p('gibson','吉布森台阶（备选）','Gibson Steps','Gibson_Steps','https://www.parks.vic.gov.au/places-to-see/parks/port-campbell-national-park','近海平面感受石灰岩海岸；海况或停车不理想时直接跳过。','先看潮汐、风浪与现场封闭标识；不翻越护栏。','距十二门徒观景区不远。','Apollo Bay 出发前吃饱。','近距离海蚀崖与海滩','能否下行取决于海况与现场公告。'),
  p('apostles','十二门徒日落','Twelve Apostles','Twelve_Apostles_(Victoria)','https://www.parks.vic.gov.au/places-to-see/parks/port-campbell-national-park','大洋路最具标志性的石灰岩海柱群；早到看人少的光线，傍晚再回观景台看日落。','白天与洛阿德峡谷错峰安排；日落前回官方观景步道，天黑后直接返回 Port Campbell。','Port Campbell National Park, Victoria。','午餐放在 Port Campbell，日落后在镇上晚餐。','南大洋海蚀石灰岩柱与日落色彩','停车和人流会波动；强风时远离悬崖边，不安排崖边夜间停留。'),
  p('lochard','洛阿德峡谷','Loch Ard Gorge','Loch_Ard_Gorge','https://www.parks.vic.gov.au/places-to-see/parks/port-campbell-national-park','十二门徒之后细走峡谷海湾与沉船故事，是当天第二个不可压缩的主线。','只在开放步道上行走，注意强风与浪涌。','Port Campbell National Park，近坎贝尔港。','Port Campbell 小镇晚餐。','峡谷、海湾与沉船故事','步道与海况以当天现场为准。')]},
 {date:'2026-10-04',label:'D11',dateText:'10.04 · 周日',title:'西段海岸回墨尔本',route:'Port Campbell → London Bridge →（The Grotto 备选）→ Bay of Islands → 内陆回 Melbourne',places:[
  p('londonbridge','伦敦桥','London Bridge','London_Bridge_(Victoria)','https://www.parks.vic.gov.au/places-to-see/parks/bay-of-islands-coastal-park','西段保留一处形态鲜明的坍塌海拱，不将相似海蚀点全部串联。','短停观景，遵守围栏与风况提示。','Port Campbell 西侧 Great Ocean Road 沿线。','Port Campbell 出发前补给。','坍塌海拱与南大洋海景','不在上午耗尽，下午需内陆长途返城。'),
  p('grotto','石窟（备选）','The Grotto','The_Grotto_(Victoria)','https://www.parks.vic.gov.au/places-to-see/parks/bay-of-islands-coastal-park','天然石窟与潮池景观；与伦敦桥同属相近海蚀主题，时间紧时跳过。','只在指定观景区停留，不下未开放岩面。','Peterborough 附近。','沿线仅作轻补给。','石灰岩石窟与潮池','强风或海况不佳时直接略过。'),
  p('bayislands','群岛湾','Bay of Islands','Bay_of_Islands_Coastal_Park','https://www.parks.vic.gov.au/places-to-see/parks/bay-of-islands-coastal-park','把最后的主线海景留给更开阔的群岛湾，再从内陆回到墨尔本。','观景后立即启程；内陆回城约 4—5 小时（预计），须留休息余量。','Peterborough 以西海岸，后转内陆往 Melbourne。','服务区补给，抵达 Melbourne 再正餐。','开阔海岸岩柱与长线海景','当日凌晨夏令时开始，时钟拨快 1 小时。')]},
 {date:'2026-10-05',label:'D12',dateText:'10.05 · 周一',title:'开飞机体验与收尾',route:'Moorabbin 体验飞行 · 市区人文或天气缓冲 · 整理返程',places:[
  p('learn-to-fly','Moorabbin 开飞机体验','Moorabbin Airport','Moorabbin_Airport','https://learntofly.edu.au/','由教员陪同的通航体验；报到与实际飞行安排以订单为准。','提前到机场；带照片证件，确认天气、体重限制与取消条款。','Moorabbin Airport，市区东南约 30 分钟（预计）。','飞行后回市区午餐。','在教员陪同下的通航体验','产品时长与资格要求须以预约运营方为准。'),
  p('ngv-library','NGV / 州立图书馆（备选）','NGV / State Library Victoria','National_Gallery_of_Victoria','https://www.ngv.vic.gov.au/','午后作为全线天气变动后的缓冲，只选一个重点看。','确认临展预约与闭馆时间；早些回酒店整理行李。','NGV：St Kilda Rd；州立图书馆：328 Swanston St。','Southbank 或 CBD 最后一顿晚餐。','维州艺术收藏与历史阅览空间','展览与开馆时间可能调整（预计）。')]},
 {date:'2026-10-06',label:'END',dateText:'10.06 · 周二',title:'返程日',route:'不安排行程 · 提前到机场 · 留给不可控因素',places:[p('departure','返程与最后检查','Melbourne Airport','Melbourne_Airport','https://www.melbourneairport.com.au/','返程日不安排行程；若航班很早，前一日就应完成所有收尾。','确认航站楼、值机、行李与接送/还车信息。','Melbourne Airport / Tullamarine。','按航班时间在机场或住宿附近早餐。','留白本身就是行程的一部分','航班与交通以实际订单为准。')]}
];
const routeNodes=[{day:0,name:'墨尔本',lat:-37.8136,lng:144.9631},{day:1,name:'墨尔本市区',lat:-37.8222,lng:144.9768},{day:2,name:'墨尔本留白',lat:-37.805,lng:144.971},{day:3,name:'希尔斯维尔',lat:-37.653,lng:145.517},{day:4,name:'潮汐河',lat:-39.0308,lng:146.3235},{day:5,name:'吱吱海滩',lat:-39.0265,lng:146.3065},{day:5,name:'菲利普岛',lat:-38.5115,lng:145.152},{day:6,name:'半岛温泉',lat:-38.3725,lng:144.878},{day:6,name:'墨尔本',lat:-37.8136,lng:144.9631},{day:7,name:'洛恩',lat:-38.54,lng:143.975},{day:8,name:'肯尼特河',lat:-38.666,lng:143.919},{day:8,name:'奥特维海角',lat:-38.8567,lng:143.5145},{day:8,name:'阿波罗湾',lat:-38.759,lng:143.671},{day:9,name:'十二门徒',lat:-38.665,lng:143.105},{day:9,name:'坎贝尔港',lat:-38.618,lng:142.999},{day:10,name:'群岛湾',lat:-38.667,lng:142.885},{day:10,name:'墨尔本',lat:-37.8136,lng:144.9631},{day:11,name:'Moorabbin',lat:-37.975,lng:145.102},{day:12,name:'墨尔本机场',lat:-37.669,lng:144.841}];
const nav=document.querySelector('#itinerary-nav'),heading=document.querySelector('#place-heading'),cards=document.querySelector('#place-cards'),pager=document.querySelector('#day-pagination'),menuButton=document.querySelector('#menu-button'),sidebar=document.querySelector('.sidebar');let active=0,map,markers=[];
const observer='IntersectionObserver'in window?new IntersectionObserver(es=>es.filter(e=>e.isIntersecting).forEach(e=>{observer.unobserve(e.target);loadImage(e.target)}),{rootMargin:'240px 0px'}):null;
function buildNav(){nav.innerHTML=days.map((d,i)=>`<section class="day-nav"><button class="day-nav-button" type="button" data-day="${i}"><span class="day-number">${d.label}</span><span><strong>${d.title}</strong><small>${d.dateText}</small></span></button>${d.places.map(x=>`<button class="spot-nav spot-nav-${x.role}" type="button" data-day="${i}" data-spot="${x.id}">${x.role==='optional'?'○ ':''}${x.name}</button>`).join('')}</section>`).join('');nav.addEventListener('click',e=>{const b=e.target.closest('[data-day]');if(!b)return;render(Number(b.dataset.day),b.dataset.spot||null,true);sidebar.classList.remove('is-open');menuButton?.setAttribute('aria-expanded','false')})}
function reservationPanel(i){const entries=confirmations[i]||[];if(!entries.length)return'';return `<aside class="reservation-panel" aria-label="本日已确认的住宿与票券"><div class="reservation-heading"><span>已确认</span><h3>住宿与票券</h3><p>确认单含个人订单资料，请仅在同行人之间使用，勿转发公开链接。</p></div><div class="reservation-list">${entries.map(x=>`<article class="reservation-card"><strong>${x.title}</strong><small>${x.detail}</small>${x.files.length?`<div class="reservation-files">${x.files.map(([label,url])=>`<span><a href="${url}" target="_blank" rel="noopener">查看 ${label} ↗</a><a href="${url}" download>下载</a></span>`).join('')}</div>`:'<em>无附件；住宿已由同行安排确认。</em>'}</article>`).join('')}</div></aside>`}
function card(x,i){const optional=x.role==='optional',replacement=x.id==='bigdrift',booked=x.confirmed,badge=booked?'已确认 · 凭证见本页上方':replacement?'替换项 · 热气球取消且天气转稳':optional?'备选 · 时间充足再去':'主线 · 优先保留',src=x.image?`src="${x.image}"`:'';return `<article class="place-card ${optional?'is-optional':'is-main'}" id="spot-${x.id}"><div class="place-photo"><img ${src} data-wiki="${encodeURIComponent(x.wiki)}" alt="${esc(x.name)} 的实景图" loading="${i===0?'eager':'lazy'}"><div class="image-placeholder">${esc(x.name)}<small>正在载入可核验图片…</small></div><span class="photo-note">实景图：<a href="https://en.wikipedia.org/wiki/${encodeURIComponent(x.wiki)}" target="_blank" rel="noopener">Wikimedia Commons / Wikipedia ↗</a></span></div><div class="place-info"><span class="route-badge ${optional?'badge-optional':'badge-main'}">${badge}</span><span class="english">${x.displayEn}</span><h3>${x.name}（${x.displayEn}，${x.category}，${x.highlight}）</h3><p class="place-intro">${x.intro}</p><dl class="facts"><div class="fact"><dt>基础导览</dt><dd>${x.guide}</dd></div><div class="fact"><dt>地理位置</dt><dd>${x.location}</dd></div><div class="fact"><dt>可以尝试</dt><dd>${x.food}</dd></div><div class="fact"><dt>特色</dt><dd>${x.feature}</dd></div><div class="fact"><dt>提醒</dt><dd>${x.caution}</dd></div>${x.booking&&!booked?`<div class="fact"><dt>官方预约</dt><dd><a href="${x.booking.url}" target="_blank" rel="noopener">${x.booking.title} · ${x.booking.note} ↗</a></dd></div>`:''}</dl><div class="place-links">${x.booking&&!booked?`<a href="${x.booking.url}" target="_blank" rel="noopener">前往官方预约 ↗</a>`:''}<a href="${x.source}" target="_blank" rel="noopener">官方 / 资料来源 ↗</a><a href="https://en.wikipedia.org/wiki/${encodeURIComponent(x.wiki)}" target="_blank" rel="noopener">图片出处 ↗</a></div></div></article>`}
function render(i,spot=null,move=false){active=Math.max(0,Math.min(i,days.length-1));const d=days[active];document.querySelectorAll('.day-nav-button').forEach(b=>b.classList.toggle('active-day',Number(b.dataset.day)===active));document.querySelectorAll('.spot-nav').forEach(b=>b.classList.toggle('active',Number(b.dataset.day)===active));heading.innerHTML=`<div class="date-lockup"><span>${d.label}</span><strong>${d.dateText.split(' · ')[0].replace('.', '<i>/</i>')}</strong><small>${d.dateText.split(' · ')[1]}</small></div><div><span class="day-kicker">DAY PLAN · ${d.date}</span><h2>${d.title}</h2></div><p class="route-context"><b>${pace[active]}</b>${d.route}<span class="stay-info">${stay[active]}</span></p>`;cards.innerHTML=reservationPanel(active)+d.places.map(card).join('');cards.querySelectorAll('img[data-wiki]').forEach(img=>{img.addEventListener('error',()=>{delete img.dataset.tried;loadImage(img)},{once:true});if(!img.getAttribute('src'))observer?observer.observe(img):loadImage(img)});const prev=days[active-1],next=days[active+1];pager.innerHTML=`${prev?`<button type="button" data-day="${active-1}"><small>← 前一日</small><strong>${prev.label} · ${prev.title}</strong></button>`:'<span></span>'}<span class="pagination-count">${String(active+1).padStart(2,'0')} / ${String(days.length).padStart(2,'0')}</span>${next?`<button type="button" data-day="${active+1}"><small>后一日 →</small><strong>${next.label} · ${next.title}</strong></button>`:'<span></span>'}`;pager.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>render(Number(b.dataset.day),null,true)));localStorage.setItem('victoria-loop-current-day',String(active));updateMap();if(spot)requestAnimationFrame(()=>document.querySelector(`#spot-${spot}`)?.scrollIntoView({behavior:'smooth',block:'start'}));else if(move)document.querySelector('#place-content').scrollIntoView({behavior:'smooth',block:'start'})}
async function loadImage(img){if(img.dataset.tried)return;img.dataset.tried='1';const title=decodeURIComponent(img.dataset.wiki);try{const r=await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title)}`);if(r.ok){const d=await r.json(),url=d.originalimage?.source||d.thumbnail?.source;if(url){img.src=url;return}}const u=`https://en.wikipedia.org/w/api.php?action=query&format=json&origin=*&generator=search&gsrsearch=${encodeURIComponent(title)}&gsrlimit=1&prop=pageimages&piprop=thumbnail&pithumbsize=1400`,q=await fetch(u),j=await q.json(),page=Object.values(j.query?.pages||{})[0];if(page?.thumbnail?.source)img.src=page.thumbnail.source}catch{}}
function initMap(){if(!window.L)return;map=L.map('route-map',{zoomControl:false,scrollWheelZoom:false,attributionControl:true});L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:19,subdomains:'abcd',attribution:'&copy; OpenStreetMap &copy; CARTO'}).addTo(map);L.polyline(routeNodes.map(n=>[n.lat,n.lng]),{color:'#d47856',weight:4,opacity:.9,lineJoin:'round'}).addTo(map);map.fitBounds(L.latLngBounds(routeNodes.map(n=>[n.lat,n.lng])).pad(.12));updateMap()}
function updateMap(){if(!map)return;markers.forEach(m=>m.remove());markers=routeNodes.map(n=>{const on=n.day===active,icon=L.divIcon({className:'route-marker-wrap',html:`<button class="route-marker ${on?'route-marker-active':''}" aria-label="${n.name}"><span>${n.name}</span></button>`,iconSize:on?[138,38]:[105,28],iconAnchor:on?[15,19]:[10,14]}),m=L.marker([n.lat,n.lng],{icon,keyboard:false}).addTo(map);m.on('click',()=>render(n.day,null,true));return m})}
function esc(v){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function initial(){const today=new Date().toLocaleDateString('en-CA'),i=days.findIndex(d=>d.date===today),saved=Number(localStorage.getItem('victoria-loop-current-day'));return i>=0?i:Number.isInteger(saved)&&saved>=0&&saved<days.length?saved:0}
document.querySelector('#show-alerts').addEventListener('click',()=>document.querySelector('#alerts').scrollIntoView({behavior:'smooth'}));document.querySelector('#booking-hub').innerHTML=`<h3>仍待预约 / 核验</h3><p>已确认的住宿、威尔逊岬安排与企鹅归巢票已移至对应行程日，不再列在这里。以下为尚未确认的运营方或场馆官方入口；价格、余位、取消规则和最后到场时间以实际订单为准。</p><div class="booking-list">${Object.entries(bookings).filter(([id])=>pendingBookingIds.has(id)).map(([,x],i)=>`<a href="${x.url}" target="_blank" rel="noopener"><span>${String(i+1).padStart(2,'0')} · ${x.label}</span><strong>${x.title}</strong><small>${x.note} ↗</small></a>`).join('')}</div>`;menuButton?.addEventListener('click',()=>{const open=sidebar.classList.toggle('is-open');menuButton.setAttribute('aria-expanded',String(open))});buildNav();initMap();render(initial());
document.querySelector('.prep-nav')?.addEventListener('click',()=>{sidebar.classList.remove('is-open');menuButton?.setAttribute('aria-expanded','false')});
